### ISSUE TITLE
error in production build

### ISSUE THREAD

**Issue by agmmnn** [agmmnn/tauri-controls#1]
`Uncaught (in promise) Not allowed by the scope`
`TypeError: Cannot read properties of null (reading 'useState')`

<details>
<summary>Details</summary>

index-c376e050.js:40  TypeError: Cannot read properties of null (reading 'useState')
    at Y.useState (index-c376e050.js:49:6350)
    at Qv (index-c376e050.js:58:32088)
    at zc (index-c376e050.js:38:19517)
    at W0 (index-c376e050.js:40:43915)
    at V0 (index-c376e050.js:40:39687)
    at Lg (index-c376e050.js:40:39615)
    at ml (index-c376e050.js:40:39470)
    at Rs (index-c376e050.js:40:35850)
    at D0 (index-c376e050.js:40:34801)
    at C (index-c376e050.js:25:1558)
gs @ index-c376e050.js:40
index-c376e050.js:40  TypeError: Cannot read properties of null (reading 'useState')
    at Y.useState (index-c376e050.js:49:6350)
    at qv (index-c376e050.js:58:33843)
    at zc (index-c376e050.js:38:19517)
    at W0 (index-c376e050.js:40:43915)
    at V0 (index-c376e050.js:40:39687)
    at Lg (index-c376e050.js:40:39615)
    at ml (index-c376e050.js:40:39470)
    at Rs (index-c376e050.js:40:35850)
    at D0 (index-c376e050.js:40:34801)
    at C (index-c376e050.js:25:1558)
gs @ index-c376e050.js:40
index-c376e050.js:40  TypeError: Cannot read properties of null (reading 'useState')
    at Y.useState (index-c376e050.js:49:6350)
    at Xv (index-c376e050.js:58:30923)
    at zc (index-c376e050.js:38:19517)
    at W0 (index-c376e050.js:40:43915)
    at V0 (index-c376e050.js:40:39687)
    at Lg (index-c376e050.js:40:39615)
    at ml (index-c376e050.js:40:39470)
    at Rs (index-c376e050.js:40:35850)
    at D0 (index-c376e050.js:40:34801)
    at C (index-c376e050.js:25:1558)
gs @ index-c376e050.js:40
index-c376e050.js:40  Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at Y.useState (index-c376e050.js:49:6350)
    at Qv (index-c376e050.js:58:32088)
    at zc (index-c376e050.js:38:19517)
    at W0 (index-c376e050.js:40:43915)
    at V0 (index-c376e050.js:40:39687)
    at Lg (index-c376e050.js:40:39615)
    at ml (index-c376e050.js:40:39470)
    at Rs (index-c376e050.js:40:35850)
    at D0 (index-c376e050.js:40:34801)
    at C (index-c376e050.js:25:1558)
tauri.localhost/:1  Uncaught (in promise) Not allowed by the scope
tauri.localhost/:1  Uncaught (in promise) Not allowed by the scope
tauri.localhost/:1  Uncaught (in promise) Not allowed by the scope
tauri.localhost/:1  Uncaught (in promise) Not allowed by the scope
tauri.localhost/:1  Uncaught (in promise) Not allowed by the scope
tauri.localhost/:1  Uncaught (in promise) Not allowed by the scope

</details>

[📷](https://github.com/agmmnn/tauri-controls/assets/16024979/c836a785-b104-43df-b711-395a8d52c82d)

**Comment by agmmnn** [comment]
I think it is due to my misconfigured `tauri.conf.json` file.🤦I added this rule and now it is ok.

```json
"security": {
  "dangerousRemoteDomainIpcAccess": [
    {
      "scheme": "https",
      "domain": "tauri.localhost",
      "windows": ["main"],
      "plugins": ["os", "event", "window"]
    }
  ]
},
```

*(the other react error message was just because of the wrong npm:link development import)*
